github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
# enable for all branches in this repo (defaults to false)
    branches: true
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
# add a check to pull requests (defaults to true)
    addCheck: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
# add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false

tasks:
  - name: Cargo build
    init: |
      time cargo build
      time cargo build --release
    command: exit

vscode:
  extensions:
    - rust-lang.rust
    - belfz.search-crates-io
    - serayuzgur.crates
    - tamasfe.even-better-toml
    - swellaby.vscode-rust-test-adapter
    - streetsidesoftware.code-spell-checker
    - vadimcn.vscode-lldb
