[package]
name = "cf-env"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.72"
guid-create = "0.1.1"
http = "0.2.5"
locale-types = "0.4.0"
